CREATE DATABASE IF NOT EXISTS ETL;
USE ETL;

CREATE TABLE IF NOT EXISTS KP1 (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    INTERVAL_START_TIMESTAMP BIGINT,
    INTERVAL_END_TIMESTAMP BIGINT,
    SERVICE_ID INT,
    TOTAL_BYTES BIGINT,
    INTERVAL_PERIOD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS KP2 (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    INTERVAL_START_TIMESTAMP BIGINT,
    INTERVAL_END_TIMESTAMP BIGINT,
    CELL_ID INT,
    NUMBER_OF_UNIQUE_USERS BIGINT,
    INTERVAL_PERIOD VARCHAR(255)
);