# Generated by Django 4.2.7 on 2023-12-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commSquareApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi1',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='kpi2',
            options={'managed': False},
        ),
    ]
